#--- Jambalaya, ontologiaECG Project Properties ---
#Sun Nov 09 18:02:27 CET 2025
DataDisplayBridge\:\:relTypeGroups=<?xml version\="1.0" encoding\="UTF-8" standalone\="no"?><Groups><Group compositeColor\="-16776961" compositeEnabled\="false" name\="Class-Instance Hierarchy"><Type name\="has instance"/><Type name\="has subclass"/></Group></Groups>
Quick\ Search\ Visible=true
